DROP TABLE IF EXISTS beaches;

CREATE TABLE beaches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    spot_type TEXT NOT NULL,
    wave TEXT NOT NULL,
    offshore TEXT NOT NULL,
    tide TEXT NOT NULL,
    level TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);